stages:
  - test
  - build
  - run

lint:
  stage: test
  image: golangci/golangci-lint:v1.41.1
  script:
    - golangci-lint run -v -E gofmt -E goconst -E gocritic -E gocognit -E gocyclo
  except:
    - schedules

binary:
  stage: build
  image: golang:1.21-bookworm
  script: go build
  except:
    - schedules

check-availability:
  stage: run
  image: golang:1.21-bookworm
  variables:
    OUTPUT_FILENAME: ip.txt
    PREVIOUS_IP_FILENAME: previous_ip.txt
  before_script:
    - go build
  script:
    - |
      if [ -f "$PREVIOUS_IP_FILENAME" ]; then
        ./ip_change_notifier -d $DOMAIN -w $WEBHOOK_URL -o $OUTPUT_FILENAME -p $(cat "$PREVIOUS_IP_FILENAME")
      else
        ./ip_change_notifier -d $DOMAIN -w $WEBHOOK_URL -o $OUTPUT_FILENAME
      fi
  artifacts:
    paths:
      - $OUTPUT_FILENAME
  only:
    - schedules
